changelog:
  categories:
    - title: "\U0001F389 New Features"
      labels:
        - feature
    - title: "\U0001F41E Bug Fixes"
      labels:
        - bug
    - title: "\U0001F528 Refactoring"
      labels:
        - refactoring
    - title: "\U0001F4D4 Documentation"
      labels:
        - docs
    - title: "\U0001F6E0\uFE0F Misc"
      labels:
        - Technical Debt
        - chore
